# version: '3'
# version is now obsolete

services:
  rabbitmq-server:
    image: rabbitmq:${RABBITMQ_VERSION}
    container_name: ${RABBITMQ_CONTAINER_NAME}
    ports:
      - ${RABBITMQ_AMQP_HOST_PORT}:${RABBITMQ_AMQP_PORT}
      - ${RABBITMQ_MANAGEMENT_HOST_PORT}:${RABBITMQ_MANAGEMENT_PORT}
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_DEFAULT_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_DEFAULT_PASS}
      # https://www.rabbitmq.com/docs/vhosts
      RABBITMQ_DEFAULT_VHOST: ${RABBITMQ_DEFAULT_VHOST}
      # The RabbitMQ management plugin provides an HTTP-based API for management and monitoring of RabbitMQ nodes and clusters,
      # along with a browser-based UI and a command line tool, rabbitmqadmin
      RABBITMQ_SERVER_ADDITIONAL_ERL_ARGS: "-rabbitmq_management plugin rabbitmq_management"
    volumes:
      - ${RABBITMQ_HOST_DIRECTORY}:/var/lib/rabbitmq

  producer-consumer:
    image: producer-consumer:latest
    stdin_open: true
    tty: true
    environment:
      - RABBITMQ_HOST=rabbitmq-server
      - RABBITMQ_PORT=${RABBITMQ_AMQP_PORT}
      - RABBITMQ_USER=${RABBITMQ_DEFAULT_USER}
      - RABBITMQ_PASSWORD=${RABBITMQ_DEFAULT_PASS}
      - RABBITMQ_VIRTUAL_HOST=${RABBITMQ_DEFAULT_VHOST}
    volumes:
      - ${HOST_DIRECTORY}:/mycode
